In [2]:
import numpy as np


In [6]:
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(np.shape(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [5]:
arr2=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr2)
print(np.shape(arr2))
print(arr2[0])
arr1=np.arange(1,10,2)
print(arr1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[[1 2 3]
 [4 5 6]]
[1 3 5 7 9]


In [ ]:
arr=np.zeros((3,3))
'''for i in range(3):
    for j in range(3):
        if i==j:
            arr[i][j]=5
print(arr)''' 

np.fill_diagonal(arr, 5)
print(arr)

[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]


In [36]:
arr1=np.array([[1, 2], [4, 5]])
arr2=np.array([[6, 7], [9, 10]])
np.matmul(arr1, arr2)

array([[24, 27],
       [69, 78]])

In [37]:
arr1=np.array([1, 2])
arr2=np.array([3, 4])
np.matmul(arr1, arr2)

np.int64(11)

In [49]:
arr = np.array([1, 2, 3,4,5,6,7,8])
arr.reshape(2,4)
arr.flatten()
arr.shape

(8,)

In [51]:
'''Create a NumPy array containing numbers from 1 to 10.'''
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [52]:
'''Create an array containing even numbers from 2 to 20.'''
arr = np.arange(2, 21, 2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [53]:
'''Create an array of 10 zeros.'''
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [54]:
'''Create an array of 15 ones.'''
arr = np.ones(15)
print(arr)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [56]:
'''Create a 4×4 identity matrix.'''
arr = np.eye(4)
print(arr)  

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [58]:
'''Create a 3×5 array filled with the number 8.'''
arr = np.full((3, 5), 8)
print(arr)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [59]:
'''Create an array containing 20 equally spaced values between 5 and 50.'''
arr = np.linspace(5, 50, 20)
print(arr)


[ 5.          7.36842105  9.73684211 12.10526316 14.47368421 16.84210526
 19.21052632 21.57894737 23.94736842 26.31578947 28.68421053 31.05263158
 33.42105263 35.78947368 38.15789474 40.52631579 42.89473684 45.26315789
 47.63157895 50.        ]


In [60]:
'''Create a random 3×4 array of floating-point numbers.'''
arr = np.random.rand(3, 4)
print(arr)

[[0.59718241 0.43737812 0.53781598 0.63945051]
 [0.58359617 0.07572347 0.13467378 0.19019591]
 [0.65012657 0.1007877  0.47713678 0.42725873]]


In [61]:
'''Create a random 4×4 array of integers between 10 and 100.'''
arr = np.random.randint(10, 100, size=(4, 4))
print(arr)

[[26 58 92 50]
 [76 37 71 91]
 [82 12 82 49]
 [26 26 92 26]]


In [62]:
'''Print the following properties of an array:
•	Shape
•	Size
•	Data type
•	Number of dimensions
'''
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)
print("Number of dimensions:", arr.ndim)


Shape: (2, 3)
Size: 6
Data type: int64
Number of dimensions: 2


In [63]:
'''Reshape a 1D array containing numbers from 1 to 12 into a 3×4 matrix.'''
arr = np.arange(1, 13)
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [64]:
'''Convert a 4×5 matrix into a 1D array.'''
arr = np.arange(1, 21).reshape(4, 5)
flattened_arr = arr.flatten()   
print(flattened_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [65]:
'''Access:
•	First element
•	Last element
•	Middle element
of a NumPy array.
'''
arr = np.array([10, 20, 30, 40, 50])
first_element = arr[0]
last_element = arr[-1]
middle_index = len(arr) // 2
print("First element:", first_element)
print("Last element:", last_element)
print("Middle element:", arr[middle_index])

First element: 10
Last element: 50
Middle element: 30


In [66]:
'''Extract the first three rows from a 5×5 matrix.'''
arr = np.arange(1, 26).reshape(5, 5)
first_three_rows = arr[:3, :]
print(first_three_rows)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [67]:
'''Extract the last two columns from a matrix.'''
arr = np.arange(1, 26).reshape(5, 5)
last_two_columns = arr[:, -2:]
print(last_two_columns)

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [68]:
'''Replace all values greater than 20 with 100.'''
arr = np.arange(1, 26).reshape(5, 5)
arr[arr > 20] = 100
print(arr)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [100 100 100 100 100]]


In [69]:
'''Count the number of elements greater than 50.'''
arr = np.array([10, 20, 30, 60, 80, 90])
count_greater_than_50 = np.sum(arr > 50)
print("Number of elements greater than 50:", count_greater_than_50)

Number of elements greater than 50: 3


In [70]:
'''Create a Boolean mask for even numbers.'''
arr = np.array([1, 2, 3, 4, 5, 6])
even_mask = arr % 2 == 0
print("Boolean mask for even numbers:", even_mask)

Boolean mask for even numbers: [False  True False  True False  True]


In [71]:
'''Print only the odd numbers from an array.'''
arr = np.array([1, 2, 3, 4, 5, 6])
odd_numbers = arr[arr % 2 != 0]
print("Odd numbers:", odd_numbers)

Odd numbers: [1 3 5]


In [72]:
'''Reverse a NumPy array.'''
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)

Reversed array: [5 4 3 2 1]


In [1]:
'''Addition, Subtraction, Multiplication, Division'''
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]


In [2]:
'''Square root of every element'''
import numpy as np

a = np.array([1, 4, 9, 16, 25])

print(np.sqrt(a))

[1. 2. 3. 4. 5.]


In [3]:
'''Mean, Median, Standard Deviation, Variance'''
import numpy as np

a = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(a))
print("Median:", np.median(a))
print("Standard Deviation:", np.std(a))
print("Variance:", np.var(a))

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Variance: 200.0


In [4]:
'''Maximum and minimum values along each row'''
import numpy as np

a = np.array([
    [10, 20, 5],
    [30, 15, 25],
    [7, 40, 12]
])

print("Maximum of each row:", np.max(a, axis=1))
print("Minimum of each row:", np.min(a, axis=1))

Maximum of each row: [20 30 40]
Minimum of each row: [ 5 15  7]


In [7]:
'''Sum of each column'''
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Column sums:", np.sum(a, axis=0))

Column sums: [12 15 18]


In [8]:
'''Cumulative sum'''
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print("Cumulative sum:", np.cumsum(a))

Cumulative sum: [ 1  3  6 10 15]


In [9]:
'''Sort an array in ascending order'''
import numpy as np

a = np.array([50, 20, 40, 10, 30])

print(np.sort(a))

[10 20 30 40 50]


In [10]:
'''Sort each row of a matrix'''
import numpy as np

a = np.array([
    [30, 10, 20],
    [60, 40, 50],
    [90, 70, 80]
])

print(np.sort(a, axis=1))

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [11]:
'''Find indices of the maximum element'''
import numpy as np

a = np.array([10, 50, 20, 80, 30])

print("Index:", np.argmax(a))

Index: 3


In [12]:
'''find duplicate values'''
import numpy as np

a = np.array([1, 2, 3, 2, 4, 5, 3, 6])

values, counts = np.unique(a, return_counts=True)

duplicates = values[counts > 1]

print("Duplicate values:", duplicates)

Duplicate values: [2 3]


In [13]:
'''Merge two arrays vertically'''
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

print(np.vstack((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [14]:
'''Merge two arrays horizontally'''
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

print(np.hstack((a, b)))

[[1 2 5 6]
 [3 4 7 8]]


In [15]:
'''Split a 6×6 matrix into three equal parts'''
import numpy as np

a = np.arange(1, 37).reshape(6, 6)

parts = np.vsplit(a, 3)

print("Part 1:")
print(parts[0])

print("Part 2:")
print(parts[1])

print("Part 3:")
print(parts[2])

Part 1:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Part 2:
[[13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Part 3:
[[25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [6]:
'''Checkerboard pattern'''
import numpy as np

a = np.zeros((4, 4))

a[::2, ::2] = 1
a[1::2, 1::2] = 1

print(a)

[[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]]


In [17]:
'''Create 1–9 matrix without typing individual numbers'''
import numpy as np

a = np.arange(1, 10).reshape(3, 3)

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
'''Create 10–90 matrix using NumPy functions'''
import numpy as np

a = np.arange(10, 100, 10).reshape(3, 3)

print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [19]:
'''Find prime numbers in an array'''
import numpy as np

a = np.array([2, 4, 5, 7, 9, 11, 15, 17])

prime = []

for n in a:
    if n > 1:
        is_prime = True

        for i in range(2, int(np.sqrt(n)) + 1):
            if n % i == 0:
                is_prime = False
                break

        if is_prime:
            prime.append(n)

print("Prime numbers:", prime)

Prime numbers: [np.int64(2), np.int64(5), np.int64(7), np.int64(11), np.int64(17)]


In [20]:
'''Replace negative values with zero'''
import numpy as np

a = np.array([10, -5, 20, -8, 30])

a[a < 0] = 0

print(a)

[10  0 20  0 30]


In [21]:
'''Frequency of each unique value'''
import numpy as np

a = np.array([1, 2, 2, 3, 3, 3, 4, 4])

values, counts = np.unique(a, return_counts=True)

for i in range(len(values)):
    print(values[i], ":", counts[i])

1 : 1
2 : 2
3 : 3
4 : 2


In [22]:
'''Random marks — 100 students, 5 subjects'''
import numpy as np

marks = np.random.randint(0, 101, (100, 5))

# Student-wise average
student_avg = np.mean(marks, axis=1)

# Subject-wise average
subject_avg = np.mean(marks, axis=0)

# Highest scorer
highest = np.argmax(student_avg)

# Lowest scorer
lowest = np.argmin(student_avg)

print("Student-wise average:")
print(student_avg)

print("Subject-wise average:")
print(subject_avg)

print("Highest scorer: Student", highest + 1)
print("Lowest scorer: Student", lowest + 1)

Student-wise average:
[54.8 41.  73.4 76.4 58.8 47.6 54.2 57.2 73.4 61.4 46.8 51.2 75.6 50.2
 49.  42.6 27.2 39.8 64.  46.  57.  73.2 47.8 42.2 30.  17.  62.8 46.2
 31.4 62.4 49.8 72.4 50.8 65.  53.4 41.8 58.8 58.  44.6 62.6 66.4 34.4
 48.8 52.6 45.6 47.4 43.4 35.8 32.8 63.2 69.  51.8 41.6 38.8 37.  42.
 48.  61.8 59.2 44.  39.2 70.2 47.2 59.8 33.4 39.  51.4 54.4 40.2 36.2
 42.  56.6 26.2 60.6 58.4 65.6 28.  28.  64.6 48.2 59.6 39.6 71.  26.2
 65.2 35.6 40.4 20.8 77.8 42.  65.2 57.4 56.  43.6 36.2 43.8 56.6 56.
 68.8 31.8]
Subject-wise average:
[49.19 50.24 52.66 51.2  47.92]
Highest scorer: Student 89
Lowest scorer: Student 26


In [23]:
'''Random rainfall for 365 days'''
import numpy as np

rainfall = np.random.randint(0, 151, 365)

print("Maximum rainfall:", np.max(rainfall))
print("Average rainfall:", np.mean(rainfall))

days = np.sum(rainfall > 80)

print("Days with rainfall > 80 mm:", days)

Maximum rainfall: 150
Average rainfall: 72.85479452054794
Days with rainfall > 80 mm: 162


In [24]:
'''Sales data — 12 months, 5 products'''
import numpy as np

sales = np.random.randint(100, 1000, (12, 5))

# Total sales of each product
product_sales = np.sum(sales, axis=0)

# Best-selling product
best_product = np.argmax(product_sales)

# Total sales of each month
monthly_sales = np.sum(sales, axis=1)

# Highest sales month
best_month = np.argmax(monthly_sales)

# Average monthly sales
average_monthly_sales = np.mean(monthly_sales)

print("Best-selling product: Product", best_product + 1)
print("Highest sales month: Month", best_month + 1)
print("Average monthly sales:", average_monthly_sales)

Best-selling product: Product 5
Highest sales month: Month 2
Average monthly sales: 2994.5833333333335


In [25]:
'''Random 256×256 grayscale image'''
import numpy as np

image = np.random.randint(0, 256, (256, 256))

print("Average pixel intensity:", np.mean(image))
print("Brightest pixel:", np.max(image))
print("Darkest pixel:", np.min(image))

Average pixel intensity: 127.28041076660156
Brightest pixel: 255
Darkest pixel: 0


In [26]:
'''Employee salary analysis'''
import numpy as np

salary = np.random.randint(20000, 100000, 20)

average = np.mean(salary)

# Employees earning above average
above_average = salary[salary > average]

# Highest salary
highest = np.max(salary)

# Lowest salary
lowest = np.min(salary)

# Top 10 salaries
top_10 = np.sort(salary)[-10:][::-1]

print("Salaries:")
print(salary)

print("Average salary:", average)

print("Employees earning above average:")
print(above_average)

print("Highest salary:", highest)

print("Lowest salary:", lowest)

print("Top 10 salaries:")
print(top_10)

Salaries:
[20362 78689 75050 90751 78807 66099 52856 89369 53634 37717 20986 72256
 32533 40941 38648 76472 45329 59740 62356 52005]
Average salary: 57230.0
Employees earning above average:
[78689 75050 90751 78807 66099 89369 72256 76472 59740 62356]
Highest salary: 90751
Lowest salary: 20362
Top 10 salaries:
[90751 89369 78807 78689 76472 75050 72256 66099 62356 59740]
